[project]
name = "dropzone47"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot>=22.3",
    "yt-dlp>=2025.8.27",
    "python-dotenv>=1.0.1",
]
