name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -e .

      - name: Verify project imports and byte-compile
        run: |
          python - << 'PY'
          import importlib.util, sys
          spec = importlib.util.spec_from_file_location('app', 'main.py')
          mod = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(mod)
          print('Import OK')
          PY
          python -m compileall -q .

